#!/bin/bash
export APP_HOME=$(pwd -P)
export PROJECT_DIR=${APP_HOME#*/src/}
export APP_NAME=$(basename $APP_HOME)
export X_OS_TYPE=$(uname)
GOPATH=${GOPATH#:}

echo '[1] initializing project'
KATE_DIR=$GOPATH/src/github.com/k81/kate
SKEL_DIR=$KATE_DIR/skel

if [ -z $SKEL_DIR ]; then
    echo "skel dir not found"
    exit 1
fi

cp -Rf $SKEL_DIR/* ./
cp -f $SKEL_DIR/.gitignore ./

function do_inflate() {
    f=$1
    #echo "inflating ... $f"
    if [ $X_OS_TYPE = 'Darwin' ];then
        sed -i '' -e "s:__APP_NAME__:$APP_NAME:g" $f
        sed -i '' -e "s:__PROJECT_DIR__:$PROJECT_DIR:g" $f
    else
        sed -i -e "s:__APP_NAME__:$APP_NAME:g" $f
        sed -i -e "s:__PROJECT_DIR__:$PROJECT_DIR:g" $f
    fi
}

export -f do_inflate
find . -type f -print |grep -v .git|xargs -n 1 -P 10 -I {} bash -c 'do_inflate "$@"' _ {}

mv "${APP_HOME}/app/__APP_NAME__/" "${APP_HOME}/app/${APP_NAME}/"

echo '[2] done.'
